openapi: 3.0.2
info:
  title: metadata-api AWSAccount Region API
  version: '1.2'
tags:
- name: Region
paths:
  /api/v1/internal/region/:
    get:
      tags:
      - Region
      summary: List Regions
      description: Get a list of all regions
      operationId: get_regions_internal_api_v1_internal_region__get
      parameters:
      - required: false
        schema:
          title: Is Active
          type: boolean
        name: is_active
        in: query
      - required: false
        schema:
          title: Is Public
          type: boolean
        name: is_public
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Regions Internal Api V1 Internal Region  Get
                type: array
                items:
                  $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    post:
      tags:
      - Region
      summary: Add Region
      description: Add a new region
      operationId: create_region_api_v1_internal_region__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnumCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/internal/region/{region_id}/:
    get:
      tags:
      - Region
      summary: Get Region
      description: Get region details by id
      operationId: get_region_internal_api_v1_internal_region__region_id___get
      parameters:
      - required: true
        schema:
          title: Region Id
          type: integer
        name: region_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    put:
      tags:
      - Region
      summary: Update Region
      description: Update region details by id
      operationId: update_region_api_v1_internal_region__region_id___put
      parameters:
      - required: true
        schema:
          title: Region Id
          type: integer
        name: region_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnumUpdate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    delete:
      tags:
      - Region
      summary: Delete Region
      description: Delete a region record
      operationId: delete_region_api_v1_internal_region__region_id___delete
      parameters:
      - required: true
        schema:
          title: Region Id
          type: integer
        name: region_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/internal/region/text_id/{text_id}/:
    get:
      tags:
      - Region
      summary: Get Region by text id
      description: Get region details by text_id
      operationId: get_region_by_text_id_internal_api_v1_internal_region_text_id__text_id___get
      parameters:
      - required: true
        schema:
          title: Text Id
          type: string
        name: text_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/public/region/{region_id}/:
    get:
      tags:
      - Region
      summary: Get Region
      description: Get region details by id
      operationId: get_region_public_api_v1_public_region__region_id___get
      parameters:
      - required: true
        schema:
          title: Region Id
          type: integer
        name: region_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutPublic'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/public/region/:
    get:
      tags:
      - Region
      summary: List Regions
      description: Get a list of all regions
      operationId: get_regions_public_api_v1_public_region__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Regions Public Api V1 Public Region  Get
                type: array
                items:
                  $ref: '#/components/schemas/EnumOutPublic'
      security:
      - HTTPBearer: []
components:
  schemas:
    EnumOutAdmin:
      title: EnumOutAdmin
      required:
      - text_id
      - internal_name
      - is_active
      - is_public
      - id
      - created
      - modified
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
        id:
          title: Id
          type: integer
        created:
          title: Created
          type: string
          format: date-time
        modified:
          title: Modified
          type: string
          format: date-time
    EnumCreate:
      title: EnumCreate
      required:
      - text_id
      - internal_name
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    EnumOutPublic:
      title: EnumOutPublic
      required:
      - text_id
      - id
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        id:
          title: Id
          type: integer
    EnumUpdate:
      title: EnumUpdate
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://metadata-services.algoseek.com/api/v1
  description: Base URL reconciled from apis.yml
