openapi: 3.0.2
info:
  title: metadata-api AWSAccount DeliveryMethod API
  version: '1.2'
tags:
- name: DeliveryMethod
paths:
  /api/v1/internal/delivery_method/:
    get:
      tags:
      - DeliveryMethod
      summary: List Delivery Methods
      description: Get a list of all delivery methods
      operationId: get_delivery_methods_internal_api_v1_internal_delivery_method__get
      parameters:
      - required: false
        schema:
          title: Is Active
          type: boolean
        name: is_active
        in: query
      - required: false
        schema:
          title: Is Public
          type: boolean
        name: is_public
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Delivery Methods Internal Api V1 Internal Delivery Method  Get
                type: array
                items:
                  $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    post:
      tags:
      - DeliveryMethod
      summary: Add Delivery Method
      description: Add a new delivery method
      operationId: create_delivery_method_api_v1_internal_delivery_method__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnumCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/internal/delivery_method/{delivery_method_id}/:
    get:
      tags:
      - DeliveryMethod
      summary: Get Delivery Method
      description: Get delivery method details by id
      operationId: get_delivery_method_internal_api_v1_internal_delivery_method__delivery_method_id___get
      parameters:
      - required: true
        schema:
          title: Delivery Method Id
          type: integer
        name: delivery_method_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    put:
      tags:
      - DeliveryMethod
      summary: Update Delivery Method
      description: Update delivery method details by id
      operationId: update_delivery_method_api_v1_internal_delivery_method__delivery_method_id___put
      parameters:
      - required: true
        schema:
          title: Delivery Method Id
          type: integer
        name: delivery_method_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnumUpdate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    delete:
      tags:
      - DeliveryMethod
      summary: Delete Delivery Method
      description: Delete a delivery method record
      operationId: delete_delivery_method_api_v1_internal_delivery_method__delivery_method_id___delete
      parameters:
      - required: true
        schema:
          title: Delivery Method Id
          type: integer
        name: delivery_method_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/internal/delivery_method/text_id/{text_id}/:
    get:
      tags:
      - DeliveryMethod
      summary: Get Delivery Method by text id
      description: Get delivery method details by text_id
      operationId: get_delivery_method_by_text_id_internal_api_v1_internal_delivery_method_text_id__text_id___get
      parameters:
      - required: true
        schema:
          title: Text Id
          type: string
        name: text_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/public/delivery_method/{delivery_method_id}/:
    get:
      tags:
      - DeliveryMethod
      summary: Get Delivery Method
      description: Get delivery method details by id
      operationId: get_delivery_method_public_api_v1_public_delivery_method__delivery_method_id___get
      parameters:
      - required: true
        schema:
          title: Delivery Method Id
          type: integer
        name: delivery_method_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutPublic'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/public/delivery_method/:
    get:
      tags:
      - DeliveryMethod
      summary: List Delivery Methods
      description: Get a list of all delivery methods
      operationId: get_delivery_methods_public_api_v1_public_delivery_method__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Delivery Methods Public Api V1 Public Delivery Method  Get
                type: array
                items:
                  $ref: '#/components/schemas/EnumOutPublic'
      security:
      - HTTPBearer: []
components:
  schemas:
    EnumOutAdmin:
      title: EnumOutAdmin
      required:
      - text_id
      - internal_name
      - is_active
      - is_public
      - id
      - created
      - modified
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
        id:
          title: Id
          type: integer
        created:
          title: Created
          type: string
          format: date-time
        modified:
          title: Modified
          type: string
          format: date-time
    EnumCreate:
      title: EnumCreate
      required:
      - text_id
      - internal_name
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    EnumOutPublic:
      title: EnumOutPublic
      required:
      - text_id
      - id
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        id:
          title: Id
          type: integer
    EnumUpdate:
      title: EnumUpdate
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
servers:
- url: https://metadata-services.algoseek.com/api/v1
  description: Base URL reconciled from apis.yml
