openapi: 3.0.2
info:
  title: metadata-api AWSAccount StorageType API
  version: '1.2'
tags:
- name: StorageType
paths:
  /api/v1/internal/storage_type/:
    get:
      tags:
      - StorageType
      summary: List storage types
      description: Get a list of all storage types
      operationId: get_storage_types_internal_api_v1_internal_storage_type__get
      parameters:
      - required: false
        schema:
          title: Is Active
          type: boolean
        name: is_active
        in: query
      - required: false
        schema:
          title: Is Public
          type: boolean
        name: is_public
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Storage Types Internal Api V1 Internal Storage Type  Get
                type: array
                items:
                  $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    post:
      tags:
      - StorageType
      summary: Add Storage Type
      description: Add a new storage type
      operationId: create_storage_type_api_v1_internal_storage_type__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnumCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/internal/storage_type/{storage_type_id}/:
    get:
      tags:
      - StorageType
      summary: Get Storage Type
      description: Get storage type details by id
      operationId: get_storage_type_internal_api_v1_internal_storage_type__storage_type_id___get
      parameters:
      - required: true
        schema:
          title: Storage Type Id
          type: integer
        name: storage_type_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    put:
      tags:
      - StorageType
      summary: Update storage type
      description: Update storage type details by id
      operationId: update_storage_type_api_v1_internal_storage_type__storage_type_id___put
      parameters:
      - required: true
        schema:
          title: Storage Type Id
          type: integer
        name: storage_type_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnumUpdate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
    delete:
      tags:
      - StorageType
      summary: Delete storage type
      description: Delete a storage type record
      operationId: delete_storage_type_api_v1_internal_storage_type__storage_type_id___delete
      parameters:
      - required: true
        schema:
          title: Storage Type Id
          type: integer
        name: storage_type_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/internal/storage_type/text_id/{text_id}/:
    get:
      tags:
      - StorageType
      summary: Get Storage Type by text id
      description: Get storage type details by text_id
      operationId: get_storage_type_by_text_id_internal_api_v1_internal_storage_type_text_id__text_id___get
      parameters:
      - required: true
        schema:
          title: Text Id
          type: string
        name: text_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutAdmin'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/public/storage_type/{storage_type_id}/:
    get:
      tags:
      - StorageType
      summary: Get Storage Type
      description: Get storage type details by id
      operationId: get_storage_type_public_api_v1_public_storage_type__storage_type_id___get
      parameters:
      - required: true
        schema:
          title: Storage Type Id
          type: integer
        name: storage_type_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumOutPublic'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
  /api/v1/public/storage_type/:
    get:
      tags:
      - StorageType
      summary: List storage types
      description: Get a list of all storage types
      operationId: get_storage_types_public_api_v1_public_storage_type__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Storage Types Public Api V1 Public Storage Type  Get
                type: array
                items:
                  $ref: '#/components/schemas/EnumOutPublic'
      security:
      - HTTPBearer: []
components:
  schemas:
    EnumOutAdmin:
      title: EnumOutAdmin
      required:
      - text_id
      - internal_name
      - is_active
      - is_public
      - id
      - created
      - modified
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
        id:
          title: Id
          type: integer
        created:
          title: Created
          type: string
          format: date-time
        modified:
          title: Modified
          type: string
          format: date-time
    EnumCreate:
      title: EnumCreate
      required:
      - text_id
      - internal_name
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    EnumOutPublic:
      title: EnumOutPublic
      required:
      - text_id
      - id
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        id:
          title: Id
          type: integer
    EnumUpdate:
      title: EnumUpdate
      type: object
      properties:
        text_id:
          title: Text Id
          type: string
        display_name:
          title: Display Name
          type: string
        full_name:
          title: Full Name
          type: string
        description:
          title: Description
          type: string
        internal_name:
          title: Internal Name
          type: string
        is_active:
          title: Is Active
          type: boolean
        is_public:
          title: Is Public
          type: boolean
        notes:
          title: Notes
          type: string
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
